version: '3.6'

services:
  web:
    build: .
    ports:
      - '80:5000'
    volumes:
      - ./:/shortcut/
    environment:
      NODE_ENV: production
  db:
    container_name: db
    image: mongo:latest
    volumes:
      - mg:/data/db/

volumes:
  mg: